CREATE TABLE `products`(
    `id` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `price` DECIMAL(8, 2) NOT NULL,
    `tags` VARCHAR(255) NOT NULL,
    `image` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
);
CREATE TABLE `users`(
    `id` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
);
CREATE TABLE `codigos_postales`(
        `CP` INTEGER PRIMARY KEY,
    	`price` INTEGER NOT NULL,
        `Provincia` VARCHAR(255) NOT NULL,
        `Localidad` VARCHAR(255) NOT NULL
);
-- Insertar los datos proporcionados en la tabla products
INSERT INTO `products` (`id`, `name`, `price`, `image`, `tags`) VALUES
(UUID(), 'Old Prince Premium (Perro cachorro)', 6400, '/img/productos/1.webp', '["perro", "cachorro"]'),
(UUID(), 'Purina Excelent (Gato cachorro)', 5500, '/img/productos/2.webp', '["gato", "cachorro"]'),
(UUID(), 'Purina Pro Plan (Perro adulto)', 3450, '/img/productos/3.webp', '["perro", "adulto"]'),
(UUID(), 'Purina Excelent (Perro cachorro)', 6900, '/img/productos/4.webp', '["perro", "cachorro"]'),
(UUID(), 'Old Prince (Gato adulto)', 2440, '/img/productos/5.webp', '["gato", "adulto"]'),
(UUID(), 'Wishkas (Gato adulto)', 9000, '/img/productos/6.webp', '["gato", "adulto"]'),
(UUID(), 'Agility (Perro adulto)', 9000, '/img/productos/7.webp', '["perro", "adulto"]'),
(UUID(), 'Pro Plan (Perro adulto)', 9000, '/img/productos/8.webp', '["perro", "adulto"]'),
(UUID(), 'Therapy (Perro adulto)', 9000, '/img/productos/9.webp', '["perro", "adulto"]');

-- Insertra codigos postales
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5435, 'Mendoza', 'Campo De Batalla', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5500, 'Mendoza', 'C D Ls Potrerillos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5500, 'Mendoza', 'Cerro Aconcagua', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5500, 'Mendoza', 'Mendoza', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5500, 'Mendoza', 'P De Las Vacas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5500, 'Mendoza', 'Plaza De Mulas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5501, 'Mendoza', 'Godoy Cruz', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5502, 'Mendoza', '9 De Julio', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5502, 'Mendoza', 'Mendoza', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5503, 'Mendoza', 'San Francisco Del Monte', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5504, 'Mendoza', 'Godoy Cruz', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5504, 'Mendoza', 'Mendoza', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5505, 'Mendoza', 'Carrodilla', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5505, 'Mendoza', 'Carrodilla La Puntilla', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5505, 'Mendoza', 'Chacras De Coria', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5505, 'Mendoza', 'La Puntilla', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5507, 'Mendoza', 'Lujan De Cuyo', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5509, 'Mendoza', 'Agrelo', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5509, 'Mendoza', 'Anchoris', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5509, 'Mendoza', 'El Carrizal De Abajo', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5509, 'Mendoza', 'Perdriel', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5509, 'Mendoza', 'Ugarteche', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5509, 'Mendoza', 'Vistalba', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5510, 'Mendoza', 'Pareditas', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5511, 'Mendoza', 'General Gutierrez', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5512, 'Mendoza', 'San Carlos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5513, 'Mendoza', 'Barrio Jardin Luzuriaga', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5513, 'Mendoza', 'Coquimbito', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5513, 'Mendoza', 'Luzuriaga', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5513, 'Mendoza', 'Sarmiento', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5514, 'Mendoza', 'Tres Esquinas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5515, 'Mendoza', 'Maipu', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5516, 'Mendoza', 'Luzuriaga', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5517, 'Mendoza', 'Barrancas', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5517, 'Mendoza', 'Russell', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5518, 'Mendoza', 'Leandro N Alem', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5519, 'Mendoza', 'Dorrego', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5519, 'Mendoza', 'San Jose', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5519, 'Mendoza', 'San Jose De Guaymallen', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5520, 'Mendoza', 'Barrio Quimicos M.D.C.1', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5521, 'Mendoza', 'Guaymallen', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5521, 'Mendoza', 'Villa Nueva', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5521, 'Mendoza', 'Villa Nueva De Guaymallen', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5522, 'Mendoza', 'Coquimbito', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5523, 'Mendoza', 'Buena Nueva', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5523, 'Mendoza', 'Capilla Del Rosario', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5524, 'Mendoza', 'C.Los Andes', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5524, 'Mendoza', 'Colonia Cano', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5525, 'Mendoza', 'Colonia Segovia', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5525, 'Mendoza', 'Rodeo De La Cruz', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5526, 'Mendoza', 'Dorrego', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5526, 'Mendoza', 'Los Campamentos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5527, 'Mendoza', 'La Primavera', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5527, 'Mendoza', 'Los Corralitos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5528, 'Mendoza', 'Chacras De Coria', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5529, 'Mendoza', 'Colonia Bombal', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5529, 'Mendoza', 'Rodeo Del Medio', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5530, 'Mendoza', 'San Jose', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5531, 'Mendoza', 'El Paraiso', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5531, 'Mendoza', 'Fray Luis Beltran', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5532, 'Mendoza', 'Minelli', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'Algarrobo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'Bermejo', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'Colonia Italiana', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'El Chilcal', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'El Sauce', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'Jocoli Viejo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'La Pega', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'Lavalle', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5533, 'Mendoza', 'Tulumaya', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5534, 'Mendoza', 'Mayor Drummond', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5535, 'Mendoza', 'Costa De Araujo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5535, 'Mendoza', 'San Jose', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5536, 'Mendoza', 'Mundo Nuevo', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5537, 'Mendoza', 'Arroyito', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5537, 'Mendoza', 'El Retamo', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5537, 'Mendoza', 'San Miguel', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5538, 'Mendoza', 'Philipps', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5538, 'Mendoza', 'Phillips', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Arenales', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'B De La Pampa Seca', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'B Pajaro Muerto', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Buitrera', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'C De Los Burros', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'C Del Rincon Bayo', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'C Los Dientitos', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'C Pan De Azucar', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'C Punta De Agua', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'C Puntilla Negra', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'C Riquitipanche', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Ca Del Diablo', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Casilla', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerrillos Negros', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Agua Salada', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Aguadita', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Alojamiento', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Angostura', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Aspero', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Barauca', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Bay', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Blanco', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Bravo', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Catedral', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Chiquero', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Cielo', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Cienaga', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Clementino', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Color', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Cortaderas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Cuerno', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Cupula', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro De Las Leqas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro De Los Dedos', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Del Medio', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Durazno', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro El Guanaco', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Fundicion', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Grande', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Horqueta', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Invernada', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Juan Pobre', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro L Corrales', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro La Mano', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Lagaqoso', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Manantial', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Masillas', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Melocoton', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Mexico', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Montura', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Pampa Seca', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Panta', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Ponderado', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Pozo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Puntudo', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Puquios', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro San Lorenzo', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Santa Maria', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Sapo', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Tigre', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Tolosa', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Tunduquera', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerro Yareta', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cerros Colorados', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Cto Del Tigre', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'E Casa De Piedra', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'E Cueva Del Toro', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'E El Carrizal', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'E San Martin', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'El Challao', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'El Infierno', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'El Puestito', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'El Zapallar', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Empalme Resguardo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Espejo', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Espejo Resguardado', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Estacion Uspallata', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Estancia Jocoli', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Estancia Uspallata', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Estancia Vvicencio', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Estancia Yalguaraz', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Garganta Del Leon', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'La Angostura', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'La Boveda', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'La Casa Del Tigre', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'La Fundicion', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'La Horqueta', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'La Jaula', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Las Canteras', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Las Heras', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Loma Colorada', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Loma De Los Burros', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Loma Sola', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Lomas Bayas', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Los Chacayes', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Los Tamarindos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Monte Bayo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Monumento Al Ejer', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P Agua De Zanjon', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P D Contrabandista', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P D L Coloradas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P D L Lagrima Viva', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P De Las Vacas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P Las Higueras', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P Los Alojamientos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P Los Pajaritos', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P Riquitipanche', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P S C De Arriba', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'P San Ignacio', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Pampa Yalguaraz', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Panqueua', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Po De La Cumbre', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Po De La Q Honda', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Po Del Rubio', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Po Valle Hermoso', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Portillo D Quemado', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Portillo De Indio', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Portillo Del Medio', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Portillo Del Norte', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Portillo Del Tigre', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Portillo La Pampa', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto Carrizalito', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto Chambon', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto El Peral', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto El Totoral', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto Escondido', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto Guamparito', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto La Gruta', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Puesto La Mojada', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Rodeo Grande', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'San Ignacio', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Santa Elena', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Schez D Bustamante', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Sierra Ansilta', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Sierra Del Tontal', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Tropero Sosa', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Tte B Matienzo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'V D Los C De Araya', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Vega De Los Burros', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Villavicencio', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5539, 'Mendoza', 'Vra De Las Vacas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5540, 'Mendoza', 'Las Heras', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5541, 'Mendoza', 'Algarrobal Abajo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5541, 'Mendoza', 'Algarrobal Arriba', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5541, 'Mendoza', 'E Plumerillo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5541, 'Mendoza', 'Paso Hondo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5541, 'Mendoza', 'S J Bautista Usno', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5542, 'Mendoza', 'El Plumerillo', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', '3 De Mayo', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Alto Grande', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Capdeville', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Colonia 3 De Mayo', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Colonia Alemana', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'El Caqito', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'El Resguardo', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Hornito Del Gringo', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Hornos De Moyano', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Jocoli', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Mathieu Norte', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5543, 'Mendoza', 'Moyano', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5544, 'Mendoza', 'Benegas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5544, 'Mendoza', 'Gobernador Benegas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5544, 'Mendoza', 'Perdriel', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'Cerro Bonete', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'Colon Sandalho', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'La Cortadera', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'Las Cortaderas', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'Minas Salagasta', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'P Agua De Toro', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'S De Las Higueras', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'San Alberto', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'Termas Vvicencio', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'Uspallata', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5545, 'Mendoza', 'Valle De Uspallata', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5546, 'Mendoza', 'Ugarteche', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5547, 'Mendoza', 'V Hipodromo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5547, 'Mendoza', 'Villa Hipodromo', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5548, 'Mendoza', '3 De Mayo', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5549, 'Mendoza', 'Alvarez Condarco', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5549, 'Mendoza', 'Blanco Encalada', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5549, 'Mendoza', 'Cacheuta', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5549, 'Mendoza', 'Cerro Pelado', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5549, 'Mendoza', 'El Salto', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5549, 'Mendoza', 'Guido', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5550, 'Mendoza', 'Compuertas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5551, 'Mendoza', 'Polvareda', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5552, 'Mendoza', 'Potrerillos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5553, 'Mendoza', 'La Pirata', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5553, 'Mendoza', 'Punta De Vacas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5553, 'Mendoza', 'Rio Blanco', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5554, 'Mendoza', 'Barrio Rivadavia', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5555, 'Mendoza', 'Puente Del Inca', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5556, 'Mendoza', 'Carrizal De Abajo', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5557, 'Mendoza', 'Caracoles', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5557, 'Mendoza', 'Cristo Redentor', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5557, 'Mendoza', 'La Cueva', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5557, 'Mendoza', 'Las Cuevas', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5558, 'Mendoza', 'La Libertad', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5559, 'Mendoza', 'Los Arboles', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5560, 'Mendoza', 'Tunuyan', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5560, 'Mendoza', 'Zapata', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5561, 'Mendoza', 'Cordon Del Plata', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5561, 'Mendoza', 'El Peral', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5561, 'Mendoza', 'El Zampal', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5561, 'Mendoza', 'Tupungato', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5561, 'Mendoza', 'Villa San Jose', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5562, 'Mendoza', 'Villa Bastias', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5563, 'Mendoza', 'Los Arboles De Villegas', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5563, 'Mendoza', 'Villa Seca', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5564, 'Mendoza', 'Barrio Lencina', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5565, 'Mendoza', 'Campo De Los Andes', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5565, 'Mendoza', 'Colonia Las Rosas', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5565, 'Mendoza', 'Vista Flores', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5566, 'Mendoza', 'La Colonia', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5567, 'Mendoza', 'La Consulta', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5568, 'Mendoza', 'El Mirador', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5569, 'Mendoza', 'Eugenio Bustos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5569, 'Mendoza', 'San Carlos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5569, 'Mendoza', 'Paso De Las Carretas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5570, 'Mendoza', 'Alto Del Salvador', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5570, 'Mendoza', 'Liber Gral S M', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5570, 'Mendoza', 'Libertador Gral San Martin', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5570, 'Mendoza', 'San Martin', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5571, 'Mendoza', 'Los Olmos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5571, 'Mendoza', 'Monte Caseros', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5572, 'Mendoza', 'La Colonia', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5572, 'Mendoza', 'Charras', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5573, 'Mendoza', 'Ciudad De Junin', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5573, 'Mendoza', 'Junin', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5574, 'Mendoza', 'La Central Rivadavia', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5575, 'Mendoza', 'Andrade', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5575, 'Mendoza', 'Los Arboles', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5576, 'Mendoza', 'Santa Maria De Oro', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5577, 'Mendoza', 'El Alto', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5577, 'Mendoza', 'La Ventana', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5577, 'Mendoza', 'Rivadavia', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5577, 'Mendoza', 'Vizcacheras', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5578, 'Mendoza', 'Barrio San Eduardo', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5579, 'Mendoza', 'Campamentos', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5579, 'Mendoza', 'La Central', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5579, 'Mendoza', 'Mundo Nuevo', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5579, 'Mendoza', 'Phillips', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5580, 'Mendoza', 'El Central', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5581, 'Mendoza', 'Russell', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5582, 'Mendoza', 'Ingeniero Giagnoni', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5582, 'Mendoza', 'Ricardo Lavalle', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5583, 'Mendoza', 'El Divisadero', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5584, 'Mendoza', 'Palmira', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5585, 'Mendoza', 'Barriales', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5585, 'Mendoza', 'Medrano', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5586, 'Mendoza', 'Cruz De Piedra', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5587, 'Mendoza', 'Barcala', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5587, 'Mendoza', 'Isla Chica', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5587, 'Mendoza', 'Isla Grande', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5587, 'Mendoza', 'San Roque', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5587, 'Mendoza', 'Valle Hermoso', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5588, 'Mendoza', 'Villa Seca', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5589, 'Mendoza', 'Chapanay', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5589, 'Mendoza', 'Espinillo', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'A Viuda De Perez', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Adrian Maturano', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Alejandro Perez', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Alfredo Lucero', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Alto De Los Perros', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Alto De Los Sapos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Alvarez', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ana De Donaire', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Andres Perez', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Antonio Sosa', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'B Elena', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Bajada Del Perro', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Becerra', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Blas Panelo', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Boyeros', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'C Gonzales Videla', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Cadetes De Chile', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Campo El Toro', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Chacras De Lima', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Chamuscao', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Chaqaral Redondo', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Cirilo Mahona', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Clarentino Roldan', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Colonia El Regadio', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Corral De Cuero', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Corral Del Molle', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Cruz Del Yugo', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Cruz Ledesma', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Dalmiro Zapata', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Daniel Lucero', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Daniel Morgan', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Delgadillo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Dionisio Ordoqez', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Dionisio Ortubia', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Domingo Gimenez', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Domingo Lara', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Domingo Oga', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Domingo Real', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Donato Ojeda', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Doroteo Ordoqez', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Dulce', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'E La Salcedina', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'E La Vizcachera', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'E Las Vizcacheras', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'E Rosales', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'E Viuda De Gomez', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Caranchito', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Cavado Chico', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Cercado', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Chalet', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Consuelo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Gonzano', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Guerrino', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Jilguero', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Lechucito', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Perino', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Regadio', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Vaquero', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Zampal', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'El Zapatino', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Eloy Funes', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Emilio Nieta', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Epifanio Fernandez', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ernesto Alcaraz', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Estanislao Ordoqez', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Evaristo Acevedo', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Evaristo Salas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Fabriciano Rojas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Felipe Garro', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Fermin Perez', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Florencio Garro', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Florencio Molina', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Florencio Ordoqez', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Francisco Molina', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Francisco Rojas', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Fructuoso Diaz', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'German Maturano', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Gertrudis De Ojeda', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Gilberto Perez', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Gregorio Zapata', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Guillermo Donaire', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'H De Los Tordillos', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'H Garzala', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Hermenegildo Diaz', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Honorio Zapata', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Huaicos De Rufino', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ignacio Villegas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Irineo Zapata', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Isla Retamito', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'J Ortubia', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Jose Diaz', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Jose Fernandez', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Jose Lucero', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Jose R Molina', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Jose Suarez', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Juan B Dufau', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Juan H Ortiz', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Juan Millan', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Juan Zapata', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Julio Comeglio', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Junta De Los Rios', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Km 935 Dvio Fcgsm', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Caqada', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Cautiva', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Chapina', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Cola', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Cortadera', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Esquina', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Estancia', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Fortuna', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Isla', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Leona', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'La Paz', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ladislao', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ladislao Campos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Las Cruces', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Las Rosas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Las Viscacheras', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Las Vistas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Las Vizcachas', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Lino Perez', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Lisandro Escudero', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Algarrobos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Altamiques', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Colorados', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Horconcitos', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Ramblones', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Roseti', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Tamarindos', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Verdes', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Los Villegas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Lucas Donaire', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Luis Marquez', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'M Escudero', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'M Quiroga', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'M Viuda De Donaire', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Maquinista Levet', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Maravilla', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Maria Garcia', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Mario Olguin', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Matias Garro', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Mauricio Calderon', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Medardo Miranda', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Mosmota', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Natalia Donaire', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Necto Sosa', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Nestor Aguilera', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Nicolas Ordoqez', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Onotre Puebla', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'P De Las Carretas', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'P De Las Tropas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'P Del Chaqacal', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Pascual Sosa', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Paso De Las Canoas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Paulino Matura', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Pedro Castelu', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Pedro Pablo Perez', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Pquita Emb Cgsm', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puente Viejo', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puerta De La Isla', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto De Garro', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto De Olguin', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto De Orozco', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto De Petra', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto De Sosa', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto El Retamito', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto Nueras', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puesto Zampal', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Puntos De Agua', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'R Bebedera', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'R De La Pampa', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ramblon Grande', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ramon Donaire', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Ramon Gimenez', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Regino Ojeda', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Retamo', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Retamo Partido', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Rosario Gatica', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Rufino Gomez', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'S Cortis', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'San Antonio', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'San Pedro', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Santiago Romero', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Saturnino Romero', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Serviliano Ojeda', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Sixto Ledesma', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Teodoro Garro', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Teodoro Villaruel', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Teofila Acevedo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Teofilo Ruben', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Teofilo Zapata', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Tila', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Tilio Alcaraz', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Tomas Mercado', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Travesia', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Trino Rosaleso', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Vicente Muqoz', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Vicente Peletay', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Villa Antigua', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Villa La Paz', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Villa Vieja', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Viuda De Orozco', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5590, 'Mendoza', 'Zanon Canal', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'Alpatacal', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'Circunvalacion', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'El Gigantillo', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'La Favorita', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'La Jacintita', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'La Porteqa', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'La Primavera', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'Las Totoritas', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5591, 'Mendoza', 'Sopanta', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5592, 'Mendoza', 'La Dormida', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5593, 'Mendoza', 'Lunlunta', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5594, 'Mendoza', 'Gobernador Civit', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5594, 'Mendoza', 'Las Catitas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5594, 'Mendoza', 'Comandante Salas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5595, 'Mendoza', 'El Colorado', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5595, 'Mendoza', 'Ñacuñan', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5596, 'Mendoza', 'La Costa', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5596, 'Mendoza', 'Santa Rosa', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5597, 'Mendoza', '12 De Octubre', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5598, 'Mendoza', 'Baqado Verde', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5598, 'Mendoza', 'Bañado Verde', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5598, 'Mendoza', 'Desaguadero', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5598, 'Mendoza', 'P Emb Fcgsm', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5598, 'Mendoza', 'Pampita Embarcadero Fcgsm', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5598, 'Mendoza', 'Tapon', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5600, 'Mendoza', 'San Rafael', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5601, 'Mendoza', 'Capitan Montoya', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5601, 'Mendoza', 'El Toledano', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5601, 'Mendoza', 'Resolana', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5602, 'Mendoza', 'San Rafael', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'Cañada Seca', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'Colonia Elena', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'Colonia Rusa', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'Ingeniero Ballofet', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'La Llave', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'Pedro Vargas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'Rincon Del Atuel', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5603, 'Mendoza', 'Salto De Las Rosas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5605, 'Mendoza', 'Nihuil', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5605, 'Mendoza', 'Santa Teresa', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5606, 'Mendoza', 'General Ortega', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5607, 'Mendoza', 'El Algarrobal', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5607, 'Mendoza', 'Colonia Española', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5607, 'Mendoza', 'Cuadro Nacional', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5608, 'Mendoza', 'Llave Nueva', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5608, 'Mendoza', 'Llave Vieja', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5609, 'Mendoza', 'Aristides Villanueva', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5609, 'Mendoza', 'Gaspar Campos', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5609, 'Mendoza', 'Goico', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5609, 'Mendoza', 'Guadales', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5609, 'Mendoza', 'Monte Coman', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5610, 'Mendoza', 'Cerro Nevado', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'Bardas Blancas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'Coihueco', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'El Alambrado', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'El Manzano', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'El Sosneado', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'Ex Fortin Malargue', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'La Valenciana', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'Los Molles', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5611, 'Mendoza', 'Ranquil Norte', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5612, 'Mendoza', 'Las Flores', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5612, 'Mendoza', 'Valle De Las Leñas', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'Agua Botada', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'Buta Billon', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'El Chacay', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'El Vatro', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'El Zampal', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'La Junta', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'Las Vegas', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'Lonco Vacas', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'Las Loicas', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'Malargue', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5613, 'Mendoza', 'Mechanquil', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5614, 'Mendoza', 'Los Cavaos', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5615, 'Mendoza', '25 De Mayo', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5617, 'Mendoza', 'Pedro Vargas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5618, 'Mendoza', 'Pueblo Echevarrieta', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5619, 'Mendoza', 'Rama Caida', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'Los Tamarindos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'El Juncalito', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'El Nevado', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'General Alvear', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'Kilometro 56', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'Kilometro 882', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'La Pomona', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5620, 'Mendoza', 'Villa Comparto', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Agua De Torre', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Agua Escondida', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Caqadon De Bonilla', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Cerro Del Chacay', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Cerro Nevado', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Cerro Yalguaras', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Cochico', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'El Desvio', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'El Ventarron', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Estancia Chacaico', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'La California', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Los Tordillos', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'P La Caldenada', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Posta De Hierro', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Puesto Lunina', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'San Pedro De Atuel', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5621, 'Mendoza', 'Tambito', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5622, 'Mendoza', 'Villa Atuel', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5623, 'Mendoza', 'Jaime Prats', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5623, 'Mendoza', 'Soitue', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5624, 'Mendoza', 'Real Del Padre', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5625, 'Mendoza', 'Villa Veinticinco De Mayo', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5626, 'Mendoza', 'Coronel Dorrego', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5627, 'Mendoza', 'Punta Del Agua', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5628, 'Mendoza', 'Rodolfo Iselin', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5629, 'Mendoza', 'El Tropezon', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5630, 'Mendoza', 'Ingeniero Balloffet', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5631, 'Mendoza', 'Goudge', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5632, 'Mendoza', 'C Alvear Oeste', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5632, 'Mendoza', 'Colonia Alvear', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5632, 'Mendoza', 'Colonia Alvear Oeste', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5632, 'Mendoza', 'Colonia Bouquet', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5632, 'Mendoza', 'Compuertas Negras', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5632, 'Mendoza', 'El Retiro', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5632, 'Mendoza', 'Las Compuertas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5633, 'Mendoza', 'Medrano', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5633, 'Mendoza', 'Ochenta Y Cuatro', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'Bowen', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'El Banderon', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'El Buen Pastor', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'Estancia La Varita', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'Kilometro 884', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'La Montilla', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'Los Angeles', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'Los Huarpes', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'Poste De Fierro', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5634, 'Mendoza', 'Vuelta Del Zanjon', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5635, 'Mendoza', 'Las Malvinas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Canalejas', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'El Aguila', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'El Arbolito', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Favelli', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'La Mora', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Medanos Colorado', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Mojon Ocho', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Nueva Constitucion', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'P De La Corona', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'P De Los Gauchos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'P Del Buen Pastor', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'P Vuelta Dl Zanjon', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Pto Los Amarillos', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Puesto La Seqa', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5636, 'Mendoza', 'Toscal', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'Costa Del Diamante', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'El Plumerito', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'La Caqada', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'La Lechuga', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'Plumerito', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'Treinta De Octubre', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'Tres Porteñas', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'Usiyal', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'Corral De Lorca', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5637, 'Mendoza', 'Ovejeria', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5638, 'Mendoza', 'Jesus Nazareno', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5640, 'Mendoza', 'Santa Teresa', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5641, 'Mendoza', 'Primavera', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5642, 'Mendoza', 'Malena', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5643, 'Mendoza', 'M De Los Gauchos', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5644, 'Mendoza', 'El Ceibo', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5645, 'Mendoza', 'Reduccion', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5646, 'Mendoza', 'Colonia Segovia', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5647, 'Mendoza', 'La Escandinava', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5648, 'Mendoza', 'Los Compartos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5649, 'Mendoza', 'Colonia Santa Teresa', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5650, 'Mendoza', 'San Roque', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5651, 'Mendoza', 'Pedregal', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5652, 'Mendoza', 'Chilecito', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5653, 'Mendoza', 'Colonia Lambare', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5654, 'Mendoza', 'El Alto Salvador', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5655, 'Mendoza', 'Santa Blanca', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5656, 'Mendoza', 'Los Alamos', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5657, 'Mendoza', 'Espino', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5658, 'Mendoza', 'Cartellone', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5659, 'Mendoza', 'Las Colonias', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5661, 'Mendoza', 'Cordon De Plata', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5662, 'Mendoza', 'Colonia Las Rosas', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5663, 'Mendoza', 'Los Sauces', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5664, 'Mendoza', 'Lavalle V Tulumaya', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5664, 'Mendoza', 'Lavalle Villa Tulumaya', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5665, 'Mendoza', 'Vista Flores', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5666, 'Mendoza', 'El Borbollon', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5667, 'Mendoza', 'San Jose De Tupungato', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5668, 'Mendoza', 'Los Barriales', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5669, 'Mendoza', 'Rodriguez Peña', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5670, 'Mendoza', 'Buen Orden', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5671, 'Mendoza', 'Monte Caseros', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5672, 'Mendoza', 'Isla Grande', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5673, 'Mendoza', 'Villa Santa Isabel', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5674, 'Mendoza', 'Quinto Cuartel', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5675, 'Mendoza', 'El Medanito', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5676, 'Mendoza', 'Medano De Oro', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5677, 'Mendoza', 'Paraje Bebida', 2000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5678, 'Mendoza', 'Colonia Richet', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5679, 'Mendoza', 'La Legua', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5680, 'Mendoza', 'Las Lagunas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5681, 'Mendoza', 'Astica', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5682, 'Mendoza', 'San Juan Bautista Usno', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5683, 'Mendoza', 'Ingeniero Gustavo Andre', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5684, 'Mendoza', 'Iglesia', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5685, 'Mendoza', 'La Isla', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5686, 'Mendoza', 'Tudcum', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5700, 'Mendoza', 'Alto Blanco', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5700, 'Mendoza', 'Pozo Escondido', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5700, 'Mendoza', 'Santa Teresa', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5700, 'Mendoza', 'Santo Domingo', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5742, 'Mendoza', 'El Borbollon', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5772, 'Mendoza', 'Potrerillos', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5836, 'Mendoza', 'Los Sauces', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5852, 'Mendoza', 'Colonia Las Rosas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5860, 'Mendoza', 'Pareditas', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5863, 'Mendoza', 'San Carlos', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5866, 'Mendoza', 'Tres Esquinas', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5876, 'Mendoza', 'Chilecito', 2500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5906, 'Mendoza', 'Buen Orden', 5000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5914, 'Mendoza', 'La Colonia', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5922, 'Mendoza', 'Los Arboles', 1000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5928, 'Mendoza', 'Los Campamentos', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5932, 'Mendoza', 'Philipps', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5939, 'Mendoza', 'La Libertad', 4000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5948, 'Mendoza', 'Mundo Nuevo', 3000);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5983, 'Mendoza', 'Rodriguez Peña', 1500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5993, 'Mendoza', 'Los Barriales', 3500);
INSERT INTO `codigos_postales` (`CP`, `Provincia`, `Localidad`, `price`) VALUES (5995, 'Mendoza', 'San Roque', 3000);